# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json ./
RUN npm install --ignore-scripts

# Copy source code
COPY . .

# Build TypeScript code
RUN npm run build

# Start the MCP server over stdio
ENTRYPOINT ["node", "dist/index.js"]
